using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using UnityEngine;
using UnityEngine.UIElements;

public class GridManager : MonoBehaviour
{
    [Header("Grid Layout")]

    //Controls the width of the grid
    [Tooltip("Keep your aspect ratio in mind (go with multiples of 16)")]
    [SerializeField] private int gridWidth;

    //Controls the height of the grid
    [Tooltip("Keep your aspect ratio in mind (go with multiples of 9)")]
    [SerializeField] private int gridHeight;

    //Holds the tile prefab so that the code can spawn it
    [SerializeField] private Tile tilePrefab;



    [Header("City management")]

    //Controls how many cities can spawn at the start of the game
    [SerializeField] private int maxCitiesAtStart;

    //Controls the rng of the city spawning, a high value will result in more spawns
    [Tooltip("The higher the value, the more spaced out the cities will be (be warned that this may spawn lower the amount of cities that spawn)")]
    [SerializeField] private int cityRandomizationFactor;

    //Holds all the cities currently ingame
    private List<Tile> currentCities;

    //Controls how often do cities expand
    [SerializeField] private float timeBetweenCityExpansionCycles; 



    [Header("Camera control")]

    //Holds the camera's position so it can be moved at the start of the game
    [SerializeField] private Transform cam;

    //Just checks if you want the camera to be moved or not
    [SerializeField] private bool centerCamToGrid;

    private void Start()
    {
        //Generates the grid
        GenerateGrid();

        //Starts the growth cycle
        StartCoroutine(CallDevelopCities());
    }

    void GenerateGrid()
    {
        //Creates a list to store the current cities
        currentCities = new List<Tile>();

        //Takes in the height and width values to generated a grid with that many rows and columns
        for (int x = 0; x < gridWidth; x++)
        {
            for (int z = 0; z < gridHeight; z++)
            {
                //Spawns a grid tile
                var spawnedTile = Instantiate(tilePrefab, new Vector3(x, 0, z), Quaternion.identity);
                spawnedTile.name = $"Tile {x} {z}";

                //This part is just to cycle between the base and the offset colors to get a grid pattern (can be removed as needed)
                var isOffset = (x % 2 == 0 && z % 2 != 0) || (x % 2 != 0 && z % 2 == 0);

                //Generates cities
                var isCity = false;

                if (maxCitiesAtStart > currentCities.Count && Random.Range(0, cityRandomizationFactor) == 0)
                {
                    isCity = true;
                    currentCities.Add(spawnedTile);
                }

                //Failsafe spawn 1 city if no cities generated by the time we reach the last tile
                if (x == gridWidth - 1 && z == gridHeight - 1 && currentCities.Count < maxCitiesAtStart)
                {
                    isCity = true;
                    currentCities.Add(spawnedTile);
                }

                //Spawns the tile objects
                spawnedTile.Init(isOffset, isCity, x, z);
            }
        }
        

        //Moves the camera to the center of the grid if needed
        if (centerCamToGrid)
        {
            cam.transform.position = new Vector3((float)gridWidth / 2 - .5f, 10, (float)gridHeight / 2 - .5f);
            cam.transform.rotation = Quaternion.Euler(90, 0, 0);
        }
    }

    //Does a growth cycle after x amount of time
    private IEnumerator CallDevelopCities()
    {
        while (true)
        {
            yield return new WaitForSeconds(timeBetweenCityExpansionCycles);
            DevelopCities();
        }
    }

    //Makes the cities grow by one tile
    private void DevelopCities()
    {
        //Creates a list of tiles to modify (otherwise when a new city grows it would consider the new city as ungrown)
        List<Tile> cityTilesToGrow = new List<Tile>();
        foreach(var spawnedTile in currentCities)
        {
            cityTilesToGrow.Add(spawnedTile);
        }

        //Makes the cities grow
        foreach (var spawnedTile in cityTilesToGrow)
        {
            //Checks neighboring tiles if they already are cities
            var currentTileXID = spawnedTile.XID;
            var currentTileZID = spawnedTile.ZID;

            // Array to store the coordinates of the neighboring tiles
            var neighbors = new (int x, int z)[]
            {
                (currentTileXID - 1, currentTileZID), // left
                (currentTileXID + 1, currentTileZID), // right
                (currentTileXID, currentTileZID + 1), // above
                (currentTileXID, currentTileZID - 1)  // below
            };

            //Just a list of all the neighboring grass tiles so one can be chosen at random to grow the city
            List<Tile> nonCityNeighborTiles = new List<Tile>();

            // Iterate through the neighbors and perform checks
            foreach (var (x, z) in neighbors)
            {
                // Check if the coordinates are within grid bounds
                if (x >= 0 && x < gridWidth && z >= 0 && z < gridHeight)
                {
                    var neighborTile = GameObject.Find($"Tile {x} {z}").GetComponent<Tile>();

                    if (!cityTilesToGrow.Contains(neighborTile))
                    {
                        nonCityNeighborTiles.Add(neighborTile);
                    }
                }
            }


            //Pick a random neighbor
            if (nonCityNeighborTiles.Count > 0)
            {
                var randomIndex = Random.Range(0, nonCityNeighborTiles.Count);
                var randomNonCityTile = nonCityNeighborTiles[randomIndex];

                //Turns the selected random tile into a city
                randomNonCityTile.Colonize();
                currentCities.Add(randomNonCityTile);
            }
        }
    }
}


